/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MemorizeRouteImport } from './routes/memorize'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemorizeIndexRouteImport } from './routes/memorize/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as MemorizeConversionsRouteImport } from './routes/memorize/conversions'
import { Route as LearnLevelRouteImport } from './routes/learn/$level'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as LearnLevelTopicRouteImport } from './routes/learn/$level/$topic'

const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeRoute = MemorizeRouteImport.update({
  id: '/memorize',
  path: '/memorize',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeIndexRoute = MemorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemorizeRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeConversionsRoute = MemorizeConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => MemorizeRoute,
} as any)
const LearnLevelRoute = LearnLevelRouteImport.update({
  id: '/learn/$level',
  path: '/learn/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LearnLevelTopicRoute = LearnLevelTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => LearnLevelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/memorize': typeof MemorizeRouteWithChildren
  '/practice': typeof PracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/$level': typeof LearnLevelRouteWithChildren
  '/memorize/conversions': typeof MemorizeConversionsRoute
  '/guides': typeof GuidesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/memorize/': typeof MemorizeIndexRoute
  '/learn/$level/$topic': typeof LearnLevelTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/$level': typeof LearnLevelRouteWithChildren
  '/memorize/conversions': typeof MemorizeConversionsRoute
  '/guides': typeof GuidesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/memorize': typeof MemorizeIndexRoute
  '/learn/$level/$topic': typeof LearnLevelTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/memorize': typeof MemorizeRouteWithChildren
  '/practice': typeof PracticeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/$level': typeof LearnLevelRouteWithChildren
  '/memorize/conversions': typeof MemorizeConversionsRoute
  '/guides/': typeof GuidesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/memorize/': typeof MemorizeIndexRoute
  '/learn/$level/$topic': typeof LearnLevelTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/memorize'
    | '/practice'
    | '/profile'
    | '/guides/$slug'
    | '/learn/$level'
    | '/memorize/conversions'
    | '/guides'
    | '/learn'
    | '/memorize/'
    | '/learn/$level/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/practice'
    | '/profile'
    | '/guides/$slug'
    | '/learn/$level'
    | '/memorize/conversions'
    | '/guides'
    | '/learn'
    | '/memorize'
    | '/learn/$level/$topic'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/leaderboard'
    | '/memorize'
    | '/practice'
    | '/_authenticated/profile'
    | '/guides/$slug'
    | '/learn/$level'
    | '/memorize/conversions'
    | '/guides/'
    | '/learn/'
    | '/memorize/'
    | '/learn/$level/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MemorizeRoute: typeof MemorizeRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LearnLevelRoute: typeof LearnLevelRouteWithChildren
  GuidesIndexRoute: typeof GuidesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize': {
      id: '/memorize'
      path: '/memorize'
      fullPath: '/memorize'
      preLoaderRoute: typeof MemorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize/': {
      id: '/memorize/'
      path: '/'
      fullPath: '/memorize/'
      preLoaderRoute: typeof MemorizeIndexRouteImport
      parentRoute: typeof MemorizeRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize/conversions': {
      id: '/memorize/conversions'
      path: '/conversions'
      fullPath: '/memorize/conversions'
      preLoaderRoute: typeof MemorizeConversionsRouteImport
      parentRoute: typeof MemorizeRoute
    }
    '/learn/$level': {
      id: '/learn/$level'
      path: '/learn/$level'
      fullPath: '/learn/$level'
      preLoaderRoute: typeof LearnLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/learn/$level/$topic': {
      id: '/learn/$level/$topic'
      path: '/$topic'
      fullPath: '/learn/$level/$topic'
      preLoaderRoute: typeof LearnLevelTopicRouteImport
      parentRoute: typeof LearnLevelRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MemorizeRouteChildren {
  MemorizeConversionsRoute: typeof MemorizeConversionsRoute
  MemorizeIndexRoute: typeof MemorizeIndexRoute
}

const MemorizeRouteChildren: MemorizeRouteChildren = {
  MemorizeConversionsRoute: MemorizeConversionsRoute,
  MemorizeIndexRoute: MemorizeIndexRoute,
}

const MemorizeRouteWithChildren = MemorizeRoute._addFileChildren(
  MemorizeRouteChildren,
)

interface LearnLevelRouteChildren {
  LearnLevelTopicRoute: typeof LearnLevelTopicRoute
}

const LearnLevelRouteChildren: LearnLevelRouteChildren = {
  LearnLevelTopicRoute: LearnLevelTopicRoute,
}

const LearnLevelRouteWithChildren = LearnLevelRoute._addFileChildren(
  LearnLevelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  MemorizeRoute: MemorizeRouteWithChildren,
  PracticeRoute: PracticeRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LearnLevelRoute: LearnLevelRouteWithChildren,
  GuidesIndexRoute: GuidesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
